### ISSUE TITLE
Invariant Violation: Element type is invalid

### ISSUE THREAD

**Issue by kytwb** [gre/gl-react-image#18]
```js
import GLImage from 'gl-react-image'

<Surface
    ref='surface'
    height={this.state.surfaceHeight}
    width={this.state.surfaceWidth}
>
  <GLImage
      source='http://i.imgur.com/tCatS2c.jpg'
      resizeMode='stretch'
  />
</Surface>}
```

> Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

```bash
➜  mobile git:(develop) ✗ ./node_modules/.bin/react-native --version
Scanning folders for symlinks in /Users/kytwb/Workspace/poseyco/mobile/node_modules (13ms)
0.53.0
```

```bash
➜  mobile git:(develop) ✗ yarn list gl-react gl-react-native gl-react-image
yarn list v1.3.2
├─ gl-react-image@0.1.0
├─ gl-react-native@2.48.0
├─ gl-react@2.3.1
└─ react-native-image-cropper@0.4.5
   └─ gl-react-native@2.47.0
✨  Done in 1.08s.
```

I think this is being fixed with #17 but I open the issue for other people to see as I just ran into this.

**Comment by kytwb** [comment]
Fixed via #19 (was still using @0.1.0 as that's what comes with `npm install gl-react-image`).  
Also noted I need to use `gl-react` v3 for `gl-react-image` to work.

**Comment by reza7rm** [comment]
Hi the problem still persists and #17 does not address 01.0 version as I see...
